# Generated by Django 4.2.7 on 2024-02-04 12:05

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import master.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('PATIENT', 'Patient')], default='ADMIN', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(default=datetime.date(2024, 2, 5), verbose_name='تاريخ الكشف\t')),
                ('appointment_time', models.CharField(choices=[('10-11', '10 AM - 11 AM'), ('11-12', '11 AM - 12 PM'), ('12-1', '12 PM - 1 PM'), ('4-5', '4 PM - 5 PM'), ('5-6', '5 PM - 6 PM'), ('6-7', '6 PM - 7 PM')], max_length=5, verbose_name='ميعاد الكشف\t')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='الوصف')),
                ('status', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='القسم')),
                ('description', models.TextField(verbose_name='وصف القسم')),
                ('department_pic', models.ImageField(default='departments/default/logo.jpg', upload_to=master.utils.department_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], default='ذكر', max_length=6)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_pic', models.ImageField(default='doctors/default/doctor.png', upload_to=master.utils.doctors_directory_path)),
                ('specialization', models.CharField(blank=True, choices=[('طبيب استشاري', 'طبيب استشاري'), ('طبيب أخصائي', 'طبيب أخصائي'), ('طبيب ممارس', 'طبيب ممارس')], default='طبيب أخصائي', max_length=24, null=True, verbose_name='اختصاص الطبيب')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(blank=True, max_length=128)),
                ('address_2', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(default='Cairo', max_length=64)),
                ('governorate', models.CharField(choices=[('Alexandria', 'الإسكندرية'), ('Aswan', 'أسوان'), ('Asyut', 'أسيوط'), ('Beheira', 'البحيرة'), ('Beni Suef', 'بني سويف'), ('Cairo', 'القاهرة'), ('Dakahlia', 'الدقهلية'), ('Damietta', 'دمياط'), ('Faiyum', 'الفيوم'), ('Gharbia', 'الغربية'), ('Giza', 'الجيزة'), ('Ismailia', 'الإسماعيلية'), ('Kafr El Sheikh', 'كفر الشيخ'), ('Luxor', 'الأقصر'), ('Matrouh', 'مطروح'), ('Minya', 'المنيا'), ('Monufia', 'المنوفية'), ('New Valley', 'الوادي الجديد'), ('North Sinai', 'شمال سيناء'), ('Port Said', 'بورسعيد'), ('Qalyubia', 'القليوبية'), ('Qena', 'قنا'), ('Red Sea', 'البحر الأحمر'), ('Sharqia', 'الشرقية'), ('Sohag', 'سوهاج'), ('South Sinai', 'جنوب سيناء'), ('Suez', 'السويس')], default='Cairo', max_length=100, verbose_name='المحافظة')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDischargeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_report', models.TextField(verbose_name='تقرير الطبيب')),
                ('admit_date', models.DateField(auto_now_add=True, verbose_name=' تاريخ تصريح الخروج')),
                ('room_charge', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name=' حساب الغرفة')),
                ('medicine_cost', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name=' حساب الدواء')),
                ('doctor_fee', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name=' رسوم الطبيب ')),
                ('other_charge', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name=' رسوم أخرى')),
                ('is_paid', models.BooleanField(default=False)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='master.appointment', verbose_name=' الحجز الطبي')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], default='ذكر', max_length=6)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_pic', models.ImageField(default='patients/default/patient.jpg', upload_to=master.utils.patients_directory_path)),
                ('symptoms', models.CharField(max_length=100)),
                ('admitDate', models.DateField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_doctor', to='master.doctor', verbose_name='الدكتور المسؤول')),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], default='ذكر', max_length=6)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_pic', models.ImageField(default='nurses/default/nurse.jpg', upload_to=master.utils.nurses_directory_path)),
                ('shift_time', models.CharField(blank=True, choices=[('دوام صباحي', 'دوام صباحي'), ('دوام مسائي', 'دوام مسائي')], default='دوام صباحي', max_length=20, null=True, verbose_name=' فترة الدوام')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.department')),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الدواء')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المتوافرة')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='السعر')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.department', verbose_name='القسم التابع')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.location'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments_headed', to='master.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.department', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.doctor', verbose_name='الطبيب المعالج'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.patient', verbose_name='اسم الحالة'),
        ),
    ]
